### ISSUE TITLE
Version 3.0.3 breaks image support

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#647]
This morning I woke up to find that inline image rendering no longer works (I use MarkdownImages package for this).

After some investigation it seems the change is in `MarkdownEditing` syntax file in commit c755fd3ffa4341b5361fb5f0ab79fdc39b5576cb. Commit comment explains that the purpose is to *Sync with ST's default Markdown syntax*.

Has the file simply been overwritten with ST's syntax files instead of being merged? The image definitions such as `image_inline`, `image-ref` seem to have been lost in the process.

**Comment by Kshitiz-Sharma** [comment]
Clarification: I don't know anything about Sublime text plugin development, or what these syntax files are. 

After further review it doesn't seem like `image_inline` but changed from:


```
  image-inline:
    - match: |-
        (?x:
            (\!\[)                             # Images start with ![
            (?=   {{balance_square_brackets}}? # balanced square brackets, backticks, taking into account escapes etc.
                  \]                           # Closing square bracket
                  [ ]?                         # Space not allowed, but we check for it anyway to mark it as invalid
                  \(                           # Open paren
            )
         )
      captures:
        1: meta.image.inline.markdown punctuation.definition.image.begin.markdown
      push: [image-inline-attr, image-inline-after-text, image-link-text]
```

To this:
```
  image-inline:
    - match: \!\[(?={{balance_square_brackets}}?\]\()
      scope: punctuation.definition.image.begin.markdown
      push:
        - image-inline-metadata
        - image-inline-text
```
